version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: redbelt-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - APP_URL=http://localhost:8000
    networks:
      - redbelt-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redbelt-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - redbelt-network

  mysql:
    image: mysql:8
    container_name: redbelt-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - redbelt-network

  redis:
    image: redis:alpine
    container_name: redbelt-redis
    ports:
      - "6379:6379"
    networks:
      - redbelt-network

networks:
  redbelt-network:
    driver: bridge

volumes:
  mysql-data: